import { useSession } from "next-auth/react";
import Head from "next/head";
import Script from "next/script";
import Catalog from "~/components/catalog/catalog";
import SignIn from "~/components/signIn";

export default function Home() {
  const { data: sessionData, status } = useSession();

  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        type="module"
        src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
      />
      <Script
        noModule
        src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
      />
      <Script
        src="https://kit.fontawesome.com/ce54b8dfe1.js"
        crossOrigin="anonymous"
      />
      {status === "authenticated" ? (
        <Catalog sessionData={sessionData} />
      ) : (
        <SignIn />
      )}
    </>
  );
}
