import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Script from "next/script";
import { api } from "~/utils/api";

// Component for an icon
function Icon({ img, w, h }: { img: string; w: number; h: number }) {
  return <Image src={img} alt={`image-${img}`} width={w} height={h} />;
}

export default function Home() {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <Script
          type="module"
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
        />
        <Script
          noModule
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
        />
        <Script
          src="https://kit.fontawesome.com/ce54b8dfe1.js"
          crossOrigin="anonymous"
        />
      </Head>
      <main className="flex min-h-screen flex-col bg-slate-900 text-white">
        {/*   Navbar   */}
        <nav className="m-4 flex items-center justify-between">
          <div className="rounded border border-gray-100 p-3">
            <Icon img="/list.svg" w={15} h={15} />
          </div>
          <div className="flex items-center gap-2">
            <Icon img="/apple.png" w={50} h={50} />
            <div className="text-lg">Apple</div>
          </div>
          <div className="rounded border border-gray-100 p-3">
            <Icon img="/shopping-cart.svg" w={15} h={15} />
          </div>
        </nav>
      </main>
    </>
  );
}
